/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.foc.graaljsenv;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;

import org.graalvm.polyglot.Engine;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.HostAccess;

public class Main {
    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Can only accept one argument!");
            return;
        }

        String code;
        try {
            code = Files.readString(Paths.get(args[0]));
        } catch (IOException e) {
            System.out.println("Can't find the specified file!");
            return;
        }

        Engine engine = Engine.newBuilder()
          .option("engine.WarnInterpreterOnly", "false")
          .build();

        Context context = Context.newBuilder("js")
         .allowHostAccess(HostAccess.ALL)
         .allowHostClassLookup(className -> true)
         .engine(engine)
         .allowAllAccess(true)
         .allowExperimentalOptions(true)
         .option("js.nashorn-compat", "true")
         .option("js.commonjs-require", "true")
         .option("js.commonjs-require-cwd", System.getProperty("user.dir"))
         .option("js.ecmascript-version", "2022")
         .build();
        context.eval("js", code);
    }
}
